[build]
  command = "pip install mkdocs mkdocs-material && pip install lightgallery && pip install table-reader && mkdocs build"
  publish = "your_publish_directory_here"

[context.production]
  command = "pip install mkdocs mkdocs-material && pip install lightgallery && pip install table-reader && mkdocs build"

