[build]
  command = "pip install mkdocs mkdocs-material && pip install mkdocs-git-revision-date-localized-plugin && mkdocs build"
  publish = "/"

[context.production]
  command = "pip install mkdocs mkdocs-material && mkdocs build"
